name: 'user_web'
port: 8021

user_srv:
  host: '127.0.0.1'
  port: 50051

jwt:
  key: '92MJIPm*QIX33SqjAvlg@i5QA5Pglhmw'

sms:
  key: 'LTAI5t7N1SXSFdWNokU1fuZL'
  secrect: 'xUBBsz98naVqtMqgj4CuO5WxtBoN9m'
  expire: 300

redis:
  host: '192.168.42.130'
  port: 6379